[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
if = "has('nvim')"
on_i = 1
hook_source = '''
source ~/.config/nvim/plugins/deoplete.rc.vim
'''

#[[plugins]]
#repo = 'deoplete-plugins/deoplete-go'
#on_ft = 'go'
#build = 'make'
#hook_source = '''
#let g:deoplete#sources#go#gocode_binary = $GOPATH.'/bin/gocode'
#let g:deoplete#sources#go#sort_class = ['package', 'func', 'type', 'var', 'const']
#'''
