[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
if = "has('nvim')"
on_i = 1
hook_source = '''
source ~/.config/nvim/plugins/deoplete.rc.vim
'''

#[[plugins]]
#repo = 'deoplete-plugins/deoplete-go'
#on_ft = 'go'
#build = 'make'
#hook_source = '''
#let g:deoplete#sources#go#gocode_binary = $GOPATH.'/bin/gocode'
#let g:deoplete#sources#go#sort_class = ['package', 'func', 'type', 'var', 'const']
#'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
let g:neosnippet#enable_snipmate_compatibility = 1
let g:neosnippet#enable_complete_done = 1
let g:neosnippet#enable_completed_snippet = 1

" Keybindings
imap <C-k> <Plug>(neosnippet_expand_or_jump)
smap <C-k> <Plug>(neosnippet_expand_or_jump)
xmap <C-k> <Plug>(neosnippet_expand_target)

" Set the path to our snippets
let g:neosnippet#snippets_directory='~/.config/nvim/snippets'
'''
on_i  = 1
depends = ['neosnippet-snippets']
